version: '3'
services:
  frontend:
    build:
      context: ../cp-frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - '4200:4200'
    volumes:
      - '../cp-frontend:/app'
  servicecenter:
    image: servicecomb/service-center
    ports:
      - '30100:30100'
